### ISSUE TITLE
fun String.toLowerCase(): String' is deprecated. Use lowercase() instead.

### ISSUE THREAD

**Issue by andikatp** [ParthSheth021299/flutter_media_downloader#16]
I updated my gradle and kotlin to the newest version but i got this error 
```
/pub.dev/flutter_media_downloader-2.0.0/android/src/main/kotlin/com/flutter_media_downloader/flutter_media_downloader/FlutterMediaDownloaderPlugin.kt:317:32 'fun String.toLowerCase(): String' is deprecated. Use lowercase() instead.
```

**Comment by ParthSheth021299** [comment]
Okay i will fix this issue
Thank you

**Comment by M4dhav** [comment]
@andikatp in the meantime if you want to use the package please use my fork by adding this to your pubspec:

```yaml
flutter_media_downloader:
    git:
      url: https://github.com/M4dhav/flutter_media_downloader.git
```
